### ISSUE TITLE
What happened to the playground?

### ISSUE THREAD

**Issue by wasamasa** [xuchunyang/elisp-playground#5]
The external API endpoint at https://elisp-playground.xuchunyang.me/ gives me an error message in Japanese and its certificate has expired. Did someone squat your domain?

**Comment by xuchunyang** [comment]
Yes, I lost the domain.

I want to use another domain but forget how to deploy the thing.

**Comment by wasamasa** [comment]
Ah, I wanted to fork the elisp-playground, then noticed that the external API endpoint probably does not use Vercel at all.
